### ISSUE TITLE
TypeError when using collectiongain

### ISSUE THREAD

**Issue by ghostshadow** [chaudum/rgain3#38]
Since recently, when i run collectiongain on my music library, it crashes with a TypeError:

```
     ....  a bunch of file listings ....

Successfully finished 141 of 142.

Unfortunately, there were some errors:
Checking for Replay Gain information ...
  <redacted path>.m4a:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/rgain3/script/replaygain.py", line 85, in do_gain
    trackdata, albumdata = formats_map.read_gain(filename)
  File "/usr/lib/python3.9/site-packages/rgain3/rgio.py", line 375, in read_gain
    return accessor.read_gain(filename)
  File "/usr/lib/python3.9/site-packages/rgain3/rgio.py", line 67, in read_gain
    track_gain = self._read_gain_data(tags, self.TRACK_GAIN_TAG,
  File "/usr/lib/python3.9/site-packages/rgain3/rgio.py", line 81, in _read_gain_data
    gain = parse_db(tags[gain_tag][0])
  File "/usr/lib/python3.9/site-packages/rgain3/util.py", line 35, in parse_db
    if value.lower().endswith("db"):
TypeError: endswith first arg must be bytes or a tuple of bytes, not str

141 successful, 1 failed.
All finished.
```
No gain data gets written to new files.

After checking multiple directories, it appears this is related to `.m4a` files, since it only crashes, when there are any m4a files in the directory.

**System Data:**
Archlinux (rgain3 installed via AUR)
Python 3.9.2
rgain3 1.1.0

**Comment by chaudum** [comment]
Hi @ghostshadow 
The error indicates that the decibel value read from the m4a header tag is a bytes value, not a string.

```
>>> b"89.0 db".endswith("db")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: endswith first arg must be bytes or a tuple of bytes, not str
```

I need to investigate how/when this can happen, because the gain information from the file headers is read using the `mutagen` library, which should return values as `str`, not `bytes`.

**Comment by ghostshadow** [comment]
Hi @chaudum
Currently i am working with the workaround, that, when the problematic file is cached as done, the remaining files get processed normally. But, when i run without the cache, the problem still occurs.

I just noticed, that i did not mention my mutagen version in my report above ... 
Here again a list of installed packages (all of the direct dependencies + python version), maybe that helps with recreating the problem:
- python 3.9.6
- rgain3 1.1.0
- python-mutagen 1.45.1
- gst-python 1.18.4 (+ plugins-good & plugins-bad)

**Comment by Farzat07** [comment]
Happened with me as well on mp4 files.

Can't we work around this for now by converting the value to string before using endswith?

**Comment by chaudum** [comment]
@ghostshadow @Farzat07 Pushed 1.1.1 to pypi https://pypi.org/project/rgain3/1.1.1/ Let me know if your cases are fixed :)

**Comment by Farzat07** [comment]
Works perfectly, thanks 😄

**Comment by ghostshadow** [comment]
@chaudum just checked (1.1.1 is in the arch repo now), everything seems to work now. Thanks.
