### ISSUE TITLE
how to parse wav file

### ISSUE THREAD

**Issue by akahanaton** [chaudum/rgain3#58]
Hi,  how to get the replaygain info from wav file, I already installed "GStreamer" and "wavparse", but the command failed:
```
$replaygain --show 01.wav
01.wav
  <Error reading Replay Gain: UnknownFiletype('.wav')>
```

thanks

**Comment by dreua** [comment]
Maybe wav files are simply not supported, I don't see wav mentioned in the readme.

**Comment by akahanaton** [comment]
Yup, I found rsgain and it works good for me now
